In [1246]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [1247]:
htd = pd.read_csv("heart_training_data.csv")
htd_test = pd.read_csv("heart_test_data.csv")

htd.head()

age  sex  feature1  feature2  feature3 feature4  feature5  feature6  \
0  58.0  NaN       2.0     105.0     240.0        0       0.0     154.0   
1  60.0    0       3.0     150.0     240.0        0       1.0     171.0   
2  67.0    0       0.0     106.0     223.0      NaN       1.0     142.0   
3  29.0    m       1.0     130.0     204.0        0       0.0     202.0   
4  35.0    1       0.0     126.0     282.0        0       0.0     156.0   

  feature7  feature8  feature9  feature10   ID  target  
0        1       0.6       1.0        0.0  253       1  
1        0       0.9       2.0        0.0  333       1  
2        0       0.3       2.0        2.0  496       1  
3        0       0.0       2.0        0.0  446       1  
4        1       0.0       2.0        0.0  289       0

In [1248]:
import numpy as np

test_set = []

In [1249]:
# fetch only row with ID 831, part of what is needed to analyse the model 
for index, row in htd_test.iterrows():
    if(row.ID == 831):
        test_set.append(row)
        print(index, row.ID)
        
        
        
#X1_test = np.array(test_set)

#X1_test
test_set

8 831


[age           63
 sex            0
 feature1       0
 feature2     124
 feature3     197
 feature4       0
 feature5       1
 feature6     136
 feature7       1
 feature8       0
 feature9       1
 feature10      0
 ID           831
 Name: 8, dtype: object]

In [1250]:
htd.shape

(219, 14)

In [1251]:
# replace missing ages with median

impute_value1 = htd['age'].median()
impute_value2 = htd_test['age'].median()

htd['age'] = htd['age'].fillna(impute_value1) 
htd_test['age'] = htd_test['age'].fillna(impute_value2) 
#htd.dropna(subset=['age'], how='any', inplace=True)

In [1252]:
htd.shape

(219, 14)

In [1253]:
htd['sex'].value_counts(dropna=False)

1         136
0          69
NaN         8
m           2
male        2
f           1
female      1
Name: sex, dtype: int64

In [1254]:
# drop missing sex
htd.dropna(subset=['sex'], how='any', inplace=True)
htd_test.dropna(subset=['sex'], how='any', inplace=True)

In [1255]:
htd.shape

(211, 14)

In [1256]:
htd['sex'].value_counts(dropna=False)

1         136
0          69
m           2
male        2
f           1
female      1
Name: sex, dtype: int64

In [1257]:
for index, row in htd.iterrows():
    if(row.sex == 'f'):
        htd.drop(index, inplace=True)
        
    if(row.sex == 'm'):
        htd.drop(index, inplace=True)
        
    if(row.sex == 'male'):
        htd.drop(index, inplace=True)
        
    if(row.sex == 'female'):
        htd.drop(index, inplace=True) 
       
    
for index, row in htd_test.iterrows():
    if(row.sex == 'f'):
        htd_test.drop(index, inplace=True)
        
    if(row.sex == 'm'):
        htd_test.drop(index, inplace=True)
        
    if(row.sex == 'male'):
        htd_test.drop(index, inplace=True)
        
    if(row.sex == 'female'):
        htd_test.drop(index, inplace=True) 
        
        


htd.sex.astype(int)

1      0
2      0
4      1
5      0
7      1
      ..
214    1
215    1
216    1
217    1
218    0
Name: sex, Length: 205, dtype: int32

In [1258]:
htd.shape

(205, 14)

In [1259]:
#plt.scatter(heart_training_data.age, heart_training_data.target, marker="+", color="red")
# replace all other NaNs with means
#htd.head(50)

In [1260]:
_ = htd['feature1'].fillna(htd.feature1.mean(), inplace=True)
_ = htd['feature2'].fillna(htd.feature2.mean(), inplace=True)
_ = htd['feature3'].fillna(htd.feature3.mean(), inplace=True)
_ = htd['feature4'].fillna(method="ffill", inplace=True)
_ = htd['feature5'].fillna(htd.feature5.mean(), inplace=True)
_ = htd['feature6'].fillna(htd.feature6.mean(), inplace=True)
_ = htd['feature7'].fillna(method="ffill", inplace=True)
_ = htd['feature8'].fillna(htd.feature8.mean(), inplace=True)
_ = htd['feature9'].fillna(htd.feature9.mean(), inplace=True)
_ = htd['feature10'].fillna(htd.feature10.mean(), inplace=True)

_ = htd_test['age'].fillna(htd_test.age.mean(), inplace=True)
_ = htd_test['feature1'].fillna(htd_test.feature1.mean(), inplace=True)
_ = htd_test['feature2'].fillna(htd_test.feature2.mean(), inplace=True)
_ = htd_test['feature3'].fillna(htd_test.feature3.mean(), inplace=True)
_ = htd_test['feature4'].fillna(method="ffill", inplace=True)
_ = htd_test['feature5'].fillna(htd_test.feature5.mean(), inplace=True)
_ = htd_test['feature6'].fillna(htd_test.feature6.mean(), inplace=True)
_ = htd_test['feature7'].fillna(method="ffill", inplace=True)
_ = htd_test['feature8'].fillna(htd_test.feature8.mean(), inplace=True)
_ = htd_test['feature9'].fillna(htd_test.feature9.mean(), inplace=True)
_ = htd_test['feature10'].fillna(htd_test.feature10.mean(), inplace=True)

#, 'feature2', 'feature3', 'feature4', 'feature5', 'feature6', 'feature7', 'feature8', 'feature9', 'feature10'], inplace=True)

In [1261]:
htd_test.dropna(subset=['feature4'], how='any', inplace=True)

In [1262]:
htd_test.drop(0, inplace=True)
htd_test.feature4.isnull()

1     False
2     False
4     False
5     False
6     False
      ...  
88    False
89    False
91    False
92    False
93    False
Name: feature4, Length: 87, dtype: bool

In [1263]:
htd['sex'] = htd.sex.astype(int)
htd_test['sex'] = htd.sex.astype(int)

for index, row in htd.iterrows():
    if(row.feature4 == 'FALSE'):
        htd.drop(index, inplace=True)
    
    if(row.feature4 == 'False'):
        htd.drop(index, inplace=True)
        
    if(row.feature4 == 'f'):
        htd.drop(index, inplace=True)
    
    if(row.feature4 == 'false'):
        htd.drop(index, inplace=True)
        
        
for index, row in htd.iterrows():
    if(row.feature7 == 'N'):
        htd.drop(index, inplace=True)
        
    if(row.feature7 == 'Yes'):
        htd.drop(index, inplace=True)
        
    if(row.feature7 == 'Y'):
        htd.drop(index, inplace=True)
        

for index, row in htd_test.iterrows():
    if(row.feature4 == 'FALSE'):
        htd_test.drop(index, inplace=True)
    
    if(row.feature4 == 'TRUE'):
        htd_test.drop(index, inplace=True)
        
    if(row.feature4 == 'false'):
        htd_test.drop(index, inplace=True)
        
        
        
for index, row in htd_test.iterrows():
    if(row.feature7 == 'N'):
        htd_test.drop(index, inplace=True)
        
    if(row.feature7 == 'Yes'):
        htd_test.drop(index, inplace=True)
    
    if(row.feature7 == 'No'):
        htd_test.drop(index, inplace=True)
        
    if(row.feature7 == 'no'):
        htd_test.drop(index, inplace=True)
        
    if(row.feature7 == 'Y'):
        htd_test.drop(index, inplace=True)
        

htd['feature4'] = htd.feature4.astype(int)
#htd_test['feature4'] = htd.feature4.astype(int)

htd['feature7'] = htd.feature7.astype(int)
htd_test['feature7'] = htd.feature7.astype(int)


htd['age'] = htd.age.astype(int)
htd['feature1'] = htd.feature1.astype(int)
htd['feature9'] = htd.feature9.astype(int)
htd['feature10'] = htd.feature10.astype(int)
htd['feature6'] = htd.feature6.astype(int)
htd['feature7'] = htd.feature7.astype(int)
htd['feature5'] = htd.feature5.astype(int)
htd['feature4'] = htd.feature4.astype(int)
htd['feature3'] = htd.feature3.astype(int)
htd['feature2'] = htd.feature2.astype(int)


htd_test['age'] = htd_test.age.astype(int)
htd_test['feature1'] = htd_test.feature1.astype(int)
htd_test['feature9'] = htd_test.feature9.astype(int)
htd_test['feature10'] = htd_test.feature10.astype(int)
htd_test['feature6'] = htd_test.feature6.astype(int)

htd_test['feature5'] = htd_test.feature5.astype(int)
htd_test['feature4'] = htd_test.feature4.astype(int)
htd_test['feature3'] = htd_test.feature3.astype(int)
htd_test['feature2'] = htd_test.feature2.astype(int)



In [1264]:
#htd_test['feature7'] = htd_test.feature7.astype(int)
htd_test.feature7

1     0.0
2     0.0
4     1.0
5     0.0
6     NaN
     ... 
86    1.0
88    1.0
89    0.0
92    0.0
93    0.0
Name: feature7, Length: 81, dtype: float64

In [1265]:
htd.dtypes

age            int32
sex            int32
feature1       int32
feature2       int32
feature3       int32
feature4       int32
feature5       int32
feature6       int32
feature7       int32
feature8     float64
feature9       int32
feature10      int32
ID             int64
target         int64
dtype: object

In [1266]:
predictors = ['age', 'sex', 'feature1', 'feature2', 'feature3', 'feature4', 'feature5', 'feature6', 'feature7', 'feature8', 'feature9', 'feature10', 'ID']

In [1267]:
htd.dtypes

age            int32
sex            int32
feature1       int32
feature2       int32
feature3       int32
feature4       int32
feature5       int32
feature6       int32
feature7       int32
feature8     float64
feature9       int32
feature10      int32
ID             int64
target         int64
dtype: object

In [1268]:
htd_test.dropna(subset=['feature7'], how='any', inplace=True)

In [1269]:
htd_test.feature7.isnull().sum()

0

In [1270]:
# fetch only rows with ID 946, 637, 688
for index, row in htd_test.iterrows():
    if(row.ID == 946):
        test_set.append(row)
        print(index, row.ID)
    
    if(row.ID == 637):
        test_set.append(row)
        print(index, row.ID)
        
    if(row.ID == 688):
        test_set.append(row)
        print(index, row.ID)
        
 


X1_test = np.array(test_set)

X1_test

20 946.0
47 637.0
75 688.0


array([[63.0, '0', 0.0, 124.0, 197.0, '0', 1.0, 136.0, '1', 0.0, 1.0,
        0.0, 831],
       [52.0, 1.0, 1.0, 120.0, 325.0, 0.0, 1.0, 172.0, 0.0, 0.2, 2.0,
        0.0, 946.0],
       [45.0, 0.0, 3.0, 110.0, 264.0, 0.0, 1.0, 132.0, 0.0, 1.2, 1.0,
        0.0, 637.0],
       [42.0, 1.0, 0.0, 140.0, 226.0, 0.0, 1.0, 178.0, 0.0, 0.0, 1.0,
        0.0, 688.0]], dtype=object)

In [1271]:
htd_test.iloc[20]

age           45.0
sex            0.0
feature1       0.0
feature2     115.0
feature3     260.0
feature4       0.0
feature5       0.0
feature6     185.0
feature7       1.0
feature8       0.0
feature9       2.0
feature10      0.0
ID           344.0
Name: 28, dtype: float64

In [1272]:
X_train = htd[predictors].values

#X_test = htd_test[predictors].values

y_test = htd.iloc[:50,13]
x_test = htd.iloc[:50, :13]

y_train = htd['target'].values


X_train

array([[ 60.,   0.,   3., ...,   2.,   0., 333.],
       [ 67.,   0.,   0., ...,   2.,   2., 496.],
       [ 35.,   1.,   0., ...,   2.,   0., 289.],
       ...,
       [ 69.,   1.,   3., ...,   1.,   1., 432.],
       [ 46.,   1.,   0., ...,   2.,   0., 631.],
       [ 63.,   0.,   1., ...,   2.,   2., 551.]])

In [1273]:
X_test[:5]

array([[5.70e+01, 0.00e+00, 2.00e+00, 1.50e+02, 1.68e+02, 0.00e+00,
        1.00e+00, 1.74e+02, 0.00e+00, 1.60e+00, 2.00e+00, 0.00e+00,
        6.36e+02],
       [5.90e+01, 0.00e+00, 0.00e+00, 1.10e+02, 2.39e+02, 0.00e+00,
        0.00e+00, 1.42e+02, 0.00e+00, 1.20e+00, 1.00e+00, 1.00e+00,
        8.84e+02],
       [7.10e+01, 1.00e+00, 2.00e+00, 1.10e+02, 2.65e+02, 0.00e+00,
        0.00e+00, 1.30e+02, 1.00e+00, 0.00e+00, 2.00e+00, 1.00e+00,
        9.00e+02],
       [5.40e+01, 0.00e+00, 2.00e+00, 1.25e+02, 2.36e+02, 0.00e+00,
        0.00e+00, 1.52e+02, 0.00e+00, 5.00e-01, 0.00e+00, 1.00e+00,
        4.10e+02],
       [6.00e+01, 1.00e+00, 0.00e+00, 1.30e+02, 2.53e+02, 0.00e+00,
        1.00e+00, 1.44e+02, 0.00e+00, 1.40e+00, 2.00e+00, 1.00e+00,
        2.61e+02]])

In [1274]:
y_train[:5]

array([1, 1, 0, 1, 0], dtype=int64)

In [1275]:
import sklearn
from sklearn.linear_model import LogisticRegression

In [1276]:
model = LogisticRegression()

model.fit(X_train, y_train)

C:\Users\David\AppData\Local\conda\conda\envs\deeplearning\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [1277]:
y_predict = model.predict(X1_test)

y_predict

array([1, 1, 1, 1], dtype=int64)

In [1278]:
print("model score: %.3f" % model.score(x_test, y_test))

model score: 0.800
